---
title: "Överblick räder"
page-layout: full
toc: false
---
<style>
  :root {
    --background-image: url("https://res.cloudinary.com/dhmmkvcpy/image/upload/q_auto,f_auto/bgs/The%20Thalassian%20Council");
  }
</style>

Nedan ser du vårat schema för kommande vecka. Om du är intresserad av att följa med på någon av våra räder så skriver du upp dig via discord (länk till aktuellt medellande hittar du om du klickar i schemat nedan). Men innan det, säkerställ att du har tagit till dig av våran information!



```{=html}
<div class="raid-week" id="raidSchedule">
    <!-- Content populated by JavaScript -->
</div>
<script type="module" src="js/raid-schedule.js"></script>
```

## Invites - Comp > Rank > Ordning

Inför en räd tittar klassledare och officers på vilka som skrivit upp sig för räden. De planerar grupperingarna när eventet väl är låst.
Denna planering kommer så småningom ut i aktuell kanal och inbjudan skickas ut efter det.

Vi behöver fylla de roller vi behöver först och främst, efter det prioriterar vi de som har högre rank och är det många inom samma rank så prioriterar vi de som skrivit upp sig först.

::: {.details summary="Signup definitioner"}
Uppskriven
: Redo för räden

Late
: Sen ankomst, platsen kan komma att ersättas 10 minuter in i räden.

Tentative
: Osäker, vi raknar inte med dig.

Bench
: Bänk, redo att hoppa in vid behov/uppfyller inte kraven och prioriteras bort.

Absense
: Kan inte, räknas bort helt och hållet.
:::

## SR / SR+

I våra räder använder vi ett Soft Reserve system. Du går in i förväg, på länken längst ned i beskrivnignen för aktuell räd och "paxxar" något du är intresserad av. Droppar det så behöver du inte rulla emot de som inte gjort detsamma. SR > MS > OS

Med SR+ får du extra poäng var vecka du lägger samma SR, med samma spec i samma räd, normalt +10. Vi kör med en SR lista per event även om vi kör samma räd mer än en dag i veckan. Det innebär att du som lagt samma SR tre veckor i rad (tredje veckan) kan tänkas rulla `/roll 100 --> 46`; vi lägger till 20 poäng och räknar din rullning som 46+20 - `66`.

För att samla poäng behöver du medverka i räden, vi använder våra combatloggar för att synkronisera detta. Detta innebär att de som har högre rank har störe möjlighet till att få vara med i räden och samla poäng. Skulle du utebli av någon anledning och inte matchas när vi synkar så tar vi bort 10 poäng, lägger du samma SR veckan därpå har du samma poäng som veckan innan.
