## Molten Core {background-video="https://res.cloudinary.com/dhmmkvcpy/video/upload/f_mp4/video/MC_bg.mp4" background-video-loop="true" preload="auto" background-video-muted="true" background-opacity="0.5"}


::: {.notes}

`r mc_notes`

:::

:::::: {.columns}

::::: {.column width="25%" #raid style="font-size:0.55em"}

| Boss | Tid `r if (session_has_wipes(mc_session)) "| Wipes" else ""` |
|---|---|---
| Incindis | `r get_boss_time(mc_session, "Incindis")` | `r get_boss_wipes(mc_session, "Incindis")` |
| Lucifron | `r get_boss_time(mc_session, "Lucifron")` | `r get_boss_wipes(mc_session, "Lucifron")` |
| Magmadar | `r get_boss_time(mc_session, "Magmadar")` | `r get_boss_wipes(mc_session, "Magmadar")` |
| Twin Golems | `r get_boss_time(mc_session, "Twin Golems")` | `r get_boss_wipes(mc_session, "Twin Golems")` |
| Sorcerer-Thane Thaurissan | `r get_boss_time(mc_session, "Sorcerer-Thane Thaurissan")` | `r get_boss_wipes(mc_session, "Sorcerer-Thane Thaurissan")` |
| Garr | `r get_boss_time(mc_session, "Garr")` | `r get_boss_wipes(mc_session, "Garr")` |
| Shazzrah | `r get_boss_time(mc_session, "Shazzrah")` | `r get_boss_wipes(mc_session, "Shazzrah")` |
| Baron Geddon | `r get_boss_time(mc_session, "Baron Geddon")` | `r get_boss_wipes(mc_session, "Baron Geddon")` |
| Sulfuron Harbinger | `r get_boss_time(mc_session, "Sulfuron Harbinger")` | `r get_boss_wipes(mc_session, "Sulfuron Harbinger")` |
| Golemagg the Incinerator | `r get_boss_time(mc_session, "Golemagg the Incinerator")` | `r get_boss_wipes(mc_session, "Golemagg the Incinerator")` |
| Majordomo Executus | `r get_boss_time(mc_session, "Majordomo Executus")` | `r get_boss_wipes(mc_session, "Majordomo Executus")` |
| Ragnaros | `r get_boss_time(mc_session, "Ragnaros")` | `r get_boss_wipes(mc_session, "Ragnaros")` |
| Totalt | `r get_raid_duration_with_comparison(mc_session)` | |

:::::

::::: {.column style="height:100%;max-height: 100vh;"}
:::: {style="display: flex; flex-direction: column; height: 100%; min-height:0;"}
::: {#raid style="flex: 0 0 auto;"}
|   |   |`r if (session_has_links(mc_session)) "   |" else ""`
|---|---|`r if (session_has_links(mc_session)) "---|" else ""`
|Extraräd |Boonkers & Pooras|`r get_all_turtlogs_links(mc_session)`
|Onsdag| 20:00-22:00|`r get_all_vod_links(mc_session)`
:::

::: {#raid style="flex: 1 1 auto;"}

`r mc_text`

:::

::: {#raid style="flex: 0 0 auto;margin-bottom:90px"}
|Epics| 
|---|
|`r get_loot_count_by_rarity(mc_session, "Epic")`st |

```{r}
priority_list <- c(
  "Talisman of Binding Shard",
  "Bindings of the Windseeker",
  "Eye of Sulfuras",
  "Onslaught Girdle",
  "Band of Accuria",
  "Regrowth Shoulders",
  "Cauterizing Band"
)
exclude_list <- c(
  "Sulfuron Ingot"
)
```

`r create_loot_table(mc_session, priority_list, max_items = 4)`

:::

::::

:::::

::::::