## Naxxramas {background-video="https://res.cloudinary.com/dhmmkvcpy/video/upload/f_mp4/video/Naxx_bg.mp4" background-video-loop="true" preload="auto" background-video-muted="true" background-opacity="0.5"}

::: {.notes}

`r naxx_notes`

:::

:::::: {.columns}

::::: {.column width="25%" #raid style="font-size:0.55em"}

| Boss | Tid `r if (session_has_wipes(naxx_session)) "|  Wipes" else ""` |
|---|---|---
| Anub'Rekhan | `r get_boss_time(naxx_session, "Anub'Rekhan")` | `r get_boss_wipes(naxx_session, "Anub'Rekhan")` |
| Grand Widow Faerlina | `r get_boss_time_with_comparison(naxx_session, "Grand Widow Faerlina", "Anub'Rekhan")` | `r get_boss_wipes(naxx_session, "Grand Widow Faerlina")` |
| Maexxna | `r get_boss_time_with_comparison(naxx_session, "Maexxna", "Anub'Rekhan")` | `r get_boss_wipes(naxx_session, "Maexxna")` |
| Noth the Plaguebringer | `r get_boss_time(naxx_session, "Noth the Plaguebringer")` | `r get_boss_wipes(naxx_session, "Noth the Plaguebringer")` |
| Heigan the Unclean | `r get_boss_time_with_comparison(naxx_session, "Heigan the Unclean", "Noth the Plaguebringer")` | `r get_boss_wipes(naxx_session, "Heigan the Unclean")` |
| Loatheb | `r get_boss_time_with_comparison(naxx_session, "Loatheb", "Noth the Plaguebringer")` | `r get_boss_wipes(naxx_session, "Loatheb")` |
| Patchwerk | `r get_boss_time(naxx_session, "Patchwerk")` | `r get_boss_wipes(naxx_session, "Patchwerk")` |
| Grobbulus | `r get_boss_time_with_comparison(naxx_session, "Grobbulus", "Patchwerk")` | `r get_boss_wipes(naxx_session, "Grobbulus")` |
| Gluth | `r get_boss_time_with_comparison(naxx_session, "Gluth", "Patchwerk")` | `r get_boss_wipes(naxx_session, "Gluth")` |
| Thaddius | `r get_boss_time_with_comparison(naxx_session, "Thaddius", "Patchwerk")` | `r get_boss_wipes(naxx_session, "Thaddius")` |
| Instructor Razuvious | `r get_boss_time(naxx_session, "Instructor Razuvious")` | `r get_boss_wipes(naxx_session, "Instructor Razuvious")` |
| Gothik the Harvester | `r get_boss_time_with_comparison(naxx_session, "Gothik the Harvester", "Instructor Razuvious")` | `r get_boss_wipes(naxx_session, "Gothik the Harvester")` |
| The Four Horsemen | `r get_boss_time_with_comparison(naxx_session, "The Four Horsemen", "Instructor Razuvious")` | `r get_boss_wipes(naxx_session, "The Four Horsemen")` |
| Sapphiron | `r get_boss_time_with_comparison(naxx_session, "Sapphiron")` | `r get_boss_wipes(naxx_session, "Sapphiron")` |
| Kel'Thuzad | `r get_boss_time_with_comparison(naxx_session, "Kel'Thuzad")` | `r get_boss_wipes(naxx_session, "Kel'Thuzad")` |

:::::

::::: {.column style="height:100%;max-height: 100vh;"}
:::: {style="display: flex; flex-direction: column; height: 100%; min-height:0;"}
::: {#raid style="flex: 0 0 auto;"}
|   |   |`r if (session_has_links(naxx_session)) "   |" else ""`
|---|---|`r if (session_has_links(naxx_session)) "---|" else ""`
|Extraräd | Azzco (Coazz) |`r get_all_turtlogs_links(naxx_session)`
|Tisdag| 19:30-22:00|`r get_all_vod_links(naxx_session)`
:::

::: {#raid style="flex: 1 1 auto;"}

`r naxx_text`

:::

::: {#raid style="flex: 0 0 auto;margin-bottom:90px"}
|Epics| Legendaries | Plate Scraps|
|---|---|---|
|`r get_loot_count_by_rarity(naxx_session, "Epic")`st |`r get_loot_count_by_rarity(naxx_session, "Legendary")`st |`r get_item_count(naxx_session, "Wartorn Plate Scrap")`st

```{r}
#| output: asis
priority_list <- c(
  "Gressil, Dawn of Ruin",
  "Kiss of the Spider", 
  "Might of Menethil",
  "The Hungering Cold",
  "Might of the Scourge"
)
exclude_list <- c(
  "Splinter of Atiesh",
  "Wartorn Plate Scrap",
  "Wartorn Chain Scrap",
  "Wartorn Leather Scrap",
  "Necro-Knight's Garb",
  "Wartorn Cloth Scrap"
)
```

`r create_loot_table(naxx_session, priority_list, max_items = 4)`

:::

::::

:::::

::::::